global:
  scrape_interval: 15s # 수집주기
  scrape_timeout: 15s
  evaluation_interval: 2m # rule evaluation 주기

scrape_configs:
  - job_name: 'monitoring-item'
    metrics_path: '/metrics'
    scheme: 'http'

    static_configs:
      - targets: ['prometheus:9090', 'node-exporter:9100']
        labels:
          service: 'monitor'