version: '3.8'

services:
  prometheus-dev:
    container_name: prometheus-dev
    image: prom/prometheus:latest
    volumes:
      - /home/ubuntu/prometheus:/prometheus
    command:
      - -config.file=/prometheus/prometheus-config.dev.yml
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    networks:
      - backend
    user: root

  grafana-dev:
    container_name: grafana-dev
    image: grafana/grafana:latest
    volumes:
      - /home/ubuntu/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - backend
    user: root

  node-exporter:
    container_name: node-exporter-dev
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - backend

networks:
  backend:
    external: true