name: 개발서버 Grafana 배포

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 소스코드 체크아웃
      uses: actions/checkout@v3

    - name: EC2에 도커컴포즈, 프로메테우스 설정 파일 복사
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST_DEV }}
        key: ${{ secrets.KEY }}
        source: ./docker-compose.grafana.dev.yml, ./prometheus/prometheus-config.dev.yml, ./promtail/promtail-config.dev.yml
        target: /home/ubuntu

    - name: EC2 연결 및 도커컴포즈 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ubuntu
        key: ${{ secrets.KEY }} 
        script: |
            sudo docker-compose -f docker-compose.grafana.dev.yml down
            sudo docker-compose -f docker-compose.grafana.dev.yml pull
            sudo docker-compose -f docker-compose.grafana.dev.yml up -d
            sudo docker image prune -a -f
